version: 1.2.{build}
configuration: Release
skip_non_tags: true
image: WMF 5
environment:
  nodejs_version: "12"
  NuGetApiKey:
    secure: asdasd
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm test
notifications:
  - provider: Email
    to:
      - buildNotification.clijsters@gmail.com
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
